// Topic constellations: stars, intra-cluster links, cross-domain edges.
// Positions are hand-picked for the landscape (1600x1000) default view; Auto-Layout
// recalculates them from scratch based on connections.

window.CONSTELLATIONS = [
  //------------------------------------------------------------ LLM SERVING
  {
    id: "llm-serving",
    name: "LLM SERVING",
    catalog: "C-01",
    hue: 265,
    cx: 400, cy: 300,
    stars: [
      { id: "vllm",               label: "vllm",              x: 170, y: 150, mag: 1,
        desc: "vLLM ist eine Open-Source Inference-Engine für LLMs mit PagedAttention und Continuous Batching. Durchsatz-Ziel: möglichst viele gleichzeitige Requests bei maximaler GPU-Auslastung. OpenAI-kompatible API (/v1/chat/completions), unterstützt Tensor-Parallelism für Multi-GPU-Serving. De-facto-Standard für Self-Hosting von Open-Weight-Modellen (Llama, Mistral, Qwen)." },
      { id: "paged-attention",    label: "paged attention",  x: 250, y: 260, mag: 2,
        desc: "Verwaltet den KV-Cache wie virtueller Speicher: fixe Page-Blöcke statt eines zusammenhängenden Speicherbereichs pro Sequenz. Vermeidet Fragmentierung und Über-Allokation. Ermöglicht Speicher-Sharing zwischen parallelen Sampling-Requests (z. B. Beam Search, mehrere Completions). Kernidee hinter vLLMs Durchsatzvorteil gegenüber naiven Implementierungen." },
      { id: "continuous-batching", label: "cont. batching",  x: 310, y: 390, mag: 2,
        desc: "Statt statischer Batches wird nach jedem Decoding-Schritt neu gebatcht: fertige Sequenzen verlassen den Batch, neue Requests treten sofort ein. Eliminiert Idle-Zeit durch Warten auf die längste Sequenz im Batch. Auch 'in-flight batching' (Triton/TensorRT-LLM-Terminologie) genannt. Steigert GPU-Auslastung typischerweise um Faktor 2-4 gegenüber statischem Batching." },
      { id: "kv-cache",           label: "kv cache",          x: 430, y: 460, mag: 1,
        desc: "Key/Value-Tensoren aller bisherigen Tokens pro Attention-Layer, vermeidet Neuberechnung bei autoregressiver Generierung. Wächst linear mit Sequenzlänge und Batch-Größe, oft der limitierende Speicherfaktor auf der GPU, nicht die Modellgewichte selbst. Grouped-Query-Attention (GQA) reduziert die Cache-Größe durch geteilte KV-Heads über mehrere Query-Heads." },
      { id: "quantization",       label: "quantization",      x: 500, y: 340, mag: 1,
        desc: "Reduziert Präzision der Modellgewichte (FP16 → INT8/INT4) für kleineren Speicherbedarf und höheren Durchsatz. GPTQ und AWQ: Post-Training-Quantisierung mit Kalibrierungsdatensatz, minimaler Qualitätsverlust bei INT4. GGUF: Quantisierungsformat für llama.cpp/CPU-Inferenz. FP8 auf H100/H200: nativ von der Hardware unterstützt, kaum Genauigkeitsverlust gegenüber BF16." },
      { id: "tensor-parallel",    label: "tensor parallel",   x: 620, y: 240, mag: 2,
        desc: "Zerlegt einzelne Matrixmultiplikationen über mehrere GPUs (Spalten-/Zeilen-Split), NVLink/NVSwitch für Low-Latency-Kommunikation zwischen den Shards essenziell. Notwendig, wenn ein Modell nicht auf eine einzelne GPU passt (z. B. 70B+ Parameter). Orthogonal zu Pipeline-Parallelism, das Layer statt Matrizen aufteilt." },
      { id: "speculative-decoding", label: "spec. decoding",  x: 700, y: 320, mag: 2,
        desc: "Ein kleines Draft-Modell generiert mehrere Tokens vorab, das große Zielmodell verifiziert sie in einem einzigen Forward-Pass. Bei hoher Akzeptanzrate mehrere Tokens pro Zielmodell-Durchlauf statt einem. Latenzgewinn ohne Qualitätsverlust, da das Zielmodell die finale Entscheidung trifft. Medusa/EAGLE als alternative Ansätze ohne separates Draft-Modell." },
      { id: "triton-server",      label: "triton server",     x: 780, y: 480, mag: 2,
        desc: "NVIDIA Triton Inference Server als Backend-Abstraktion für verschiedene Frameworks (TensorRT-LLM, vLLM-Backend, ONNX, PyTorch). Model-Repository definiert Versionierung, Ensemble-Pipelines verketten Vor-/Nachverarbeitung mit Inferenz. In-flight Batching + dynamische Batch-Bildung nativ integriert. Metrics-Endpoint für Prometheus (Queue-Zeit, Inferenz-Latenz, GPU-Auslastung)." },
      { id: "autoscaling-gpu",    label: "gpu autoscaling",   x: 860, y: 380, mag: 2,
        desc: "Horizontales Skalieren von GPU-Pods anhand Custom-Metriken statt CPU: Queue-Länge, Tokens/Sekunde, GPU-Memory-Auslastung via KEDA + Prometheus-Adapter. Kaltstart eines GPU-Pods dauert oft Minuten (Modell-Download, CUDA-Init), Scale-to-Zero daher nur bei tolerierbarer Latenz sinnvoll. Node-Pools mit unterschiedlichen GPU-Typen (A100/H100/L40S) je nach Modellgröße." },
      { id: "prompt-caching",     label: "prompt caching",    x: 730, y: 560, mag: 3,
        desc: "Cached den KV-State für wiederkehrende Prompt-Präfixe (System-Prompt, Few-Shot-Beispiele) über mehrere Requests hinweg. Reduziert Time-to-First-Token drastisch bei langen, stabilen Präfixen. Prefix-Caching in vLLM via Hash über Token-Blöcke, automatische Wiederverwendung ohne Client-Beteiligung." },
      { id: "guided-decoding",    label: "guided decoding",   x: 420, y: 580, mag: 2,
        desc: "Erzwingt strukturierte Ausgabe (JSON-Schema, Grammatik, Regex) durch Einschränkung der Token-Wahrscheinlichkeiten pro Decoding-Schritt. Outlines/XGrammar als gängige Bibliotheken, in vLLM und TensorRT-LLM integriert. Essenziell für zuverlässige Tool-Calls, da das Modell nicht gegen ein Schema validiert werden muss, sondern es per Konstruktion einhält." },
      { id: "multi-lora",         label: "multi-lora",        x: 560, y: 150, mag: 3,
        desc: "Dutzende feingetunte LoRA-Adapter teilen sich ein Basis-Modell im GPU-Speicher, dynamisches Laden pro Request anhand eines Adapter-Namens im API-Call. Vermeidet, für jeden Kunden/Use-Case ein eigenes vollständiges Modell vorzuhalten. Adapter-Größe typischerweise wenige MB statt GB, Swap-Kosten dadurch vernachlässigbar." },
      { id: "streaming-sse",      label: "streaming sse",     x: 880, y: 560, mag: 2,
        desc: "Token-weise Ausgabe via Server-Sent Events, Client verarbeitet Text inkrementell statt auf die vollständige Antwort zu warten. OpenAI-kompatibles Chunk-Format (data: {...}\\n\\n). Time-to-First-Token als zentrale UX-Metrik, unabhängig vom Gesamtdurchsatz." },
      { id: "load-balancing",     label: "load balancing",    x: 610, y: 640, mag: 3,
        desc: "Round-Robin ist bei LLM-Inferenz ungeeignet, da Requests stark unterschiedliche Laufzeiten haben. Least-Outstanding-Requests oder Queue-Length-basiertes Routing verteilt Last realistischer. Session-Affinity für Prefix-Caching sinnvoll: gleiche Konversation möglichst zur gleichen Instanz, um Cache-Hits zu maximieren." },
    ],
    lines: [
      ["vllm", "paged-attention"],
      ["vllm", "continuous-batching"],
      ["vllm", "kv-cache"],
      ["vllm", "tensor-parallel"],
      ["vllm", "quantization"],
      ["vllm", "prompt-caching"],
      ["vllm", "guided-decoding"],
      ["vllm", "multi-lora"],
      ["paged-attention", "kv-cache"],
      ["continuous-batching", "kv-cache"],
      ["continuous-batching", "triton-server"],
      ["kv-cache", "quantization"],
      ["kv-cache", "prompt-caching"],
      ["quantization", "tensor-parallel"],
      ["tensor-parallel", "triton-server"],
      ["speculative-decoding", "vllm"],
      ["speculative-decoding", "kv-cache"],
      ["triton-server", "autoscaling-gpu"],
      ["triton-server", "load-balancing"],
      ["autoscaling-gpu", "load-balancing"],
      ["autoscaling-gpu", "multi-lora"],
      ["streaming-sse", "vllm"],
      ["streaming-sse", "load-balancing"],
      ["prompt-caching", "load-balancing"],
      ["guided-decoding", "multi-lora"],
    ],
  },

  //------------------------------------------------------------- MCP SERVER
  {
    id: "mcp",
    name: "MCP SERVER",
    catalog: "C-02",
    hue: 15,
    cx: 1180, cy: 280,
    stars: [
      { id: "mcp-protocol",       label: "mcp protocol",      x: 1110, y: 340, mag: 1,
        desc: "MCP als offener Standard (Anthropic, Nov 2024) für die Anbindung von LLMs an externe Tools und Datenquellen, basiert auf JSON-RPC 2.0. Definiert drei Primitive: Tools (Aktionen), Resources (Kontextdaten), Prompts (wiederverwendbare Templates). Client-Server-Architektur: ein Host (z. B. Claude Desktop) verwaltet mehrere MCP-Client-Verbindungen zu unabhängigen Servern." },
      { id: "server-lifecycle",   label: "server lifecycle",  x: 1240, y: 400, mag: 2,
        desc: "Initialisierung per initialize-Request mit Protocol-Version und Capabilities-Aushandlung (welche Primitive unterstützt der Server: tools, resources, prompts, sampling). Client bestätigt mit initialized-Notification. Danach erst sind reguläre Requests zulässig. Versions-Mismatch führt zum kontrollierten Verbindungsabbruch statt stillem Fehlverhalten." },
      { id: "mcp-tools",          label: "tools",             x: 1380, y: 340, mag: 1,
        desc: "Server exponiert aufrufbare Funktionen mit Namen, Beschreibung und JSON-Schema für Eingabeparameter. Das LLM entscheidet anhand der Tool-Beschreibung, wann und mit welchen Argumenten es aufgerufen wird. tools/list liefert das Schema, tools/call führt aus. Rückgabe als strukturierter Content-Block (Text, Bild, eingebettete Resource)." },
      { id: "mcp-resources",      label: "resources",         x: 980,  y: 420, mag: 2,
        desc: "Adressierbare Kontextdaten über URIs (file://, https://, custom Schemes), die der Client dem Modell als Kontext anbieten kann, ohne dass das Modell aktiv danach fragen muss. resources/list für Discovery, resources/read für Inhalt. Subscriptions (resources/subscribe) benachrichtigen den Client bei Änderungen, sinnvoll für sich ändernde Dateien oder Live-Daten." },
      { id: "mcp-prompts",        label: "prompts",           x: 1120, y: 490, mag: 3,
        desc: "Vordefinierte, parametrisierbare Prompt-Templates, die der Server bereitstellt und die im Client als Slash-Commands oder Menüpunkte auftauchen können. Trennt wiederkehrende Interaktionsmuster (Code-Review, Commit-Message) vom eigentlichen Modell-Prompting. prompts/get liefert die fertig gerenderte Nachrichtensequenz." },
      { id: "transport-stdio",    label: "stdio transport",   x: 1270, y: 540, mag: 2,
        desc: "Lokaler Transport über Standard-Input/Output: Server läuft als Subprozess, Nachrichten als zeilengetrennte JSON-Objekte. Kein Netzwerk-Overhead, kein Auth nötig, da der Host den Prozess selbst startet. Standardfall für lokale Tools (Dateisystem, Git, lokale Datenbanken) in Claude Desktop." },
      { id: "transport-http-sse", label: "http/sse transport", x: 980,  y: 560, mag: 2,
        desc: "Streamable HTTP Transport (Nachfolger von reinem HTTP+SSE) für Remote-Server: ein einzelner Endpunkt für POST-Requests, optional Server-Sent Events für Streaming-Antworten und Server-initiierte Nachrichten. Ermöglicht Multi-Client-Server über das Netzwerk, im Gegensatz zu stdio auf einen Prozess beschränkt." },
      { id: "mcp-auth",           label: "oauth 2.1",         x: 850,  y: 200, mag: 2,
        desc: "OAuth 2.1 für Remote-MCP-Server: Authorization-Code-Flow mit PKCE, dynamische Client-Registrierung. Server agiert als Resource Server, delegiert Token-Ausstellung an einen separaten Authorization Server. Notwendig, sobald ein MCP-Server über das Netzwerk erreichbar ist und nicht wie stdio implizit durch den lokalen Prozessstart vertraut wird." },
      { id: "mcp-sampling",       label: "sampling",          x: 940,  y: 310, mag: 3,
        desc: "Kehrt die übliche Richtung um: der Server fragt den Client um eine LLM-Completion, statt selbst Requests zu bedienen. Nützlich, wenn ein Tool selbst eine Modell-Entscheidung benötigt (z. B. Zusammenfassen großer Zwischenergebnisse vor der Rückgabe). Client behält volle Kontrolle: Human-in-the-loop-Bestätigung vor jeder Sampling-Anfrage ist Teil der Spezifikation." },
      { id: "mcp-roots",          label: "roots",             x: 1020, y: 200, mag: 3,
        desc: "Client teilt dem Server mit, auf welche Filesystem- oder URI-Bereiche er zugreifen darf (roots/list). Grenzt den Aktionsradius eines Tool-Servers ein, etwa auf ein einzelnes Projektverzeichnis statt das gesamte Dateisystem. Dynamische Änderungen via roots/list_changed-Notification." },
      { id: "tool-schema",        label: "tool schema",       x: 1440, y: 230, mag: 2,
        desc: "JSON-Schema-Definition der Tool-Eingabeparameter, vom Modell zur Validierung und Argument-Generierung genutzt. Präzise Typen, enums und description-Felder pro Parameter verbessern die Trefferquote korrekter Aufrufe erheblich. Schlecht dokumentierte Schemas sind die häufigste Ursache für fehlerhafte Tool-Calls." },
      { id: "mcp-sdk",            label: "sdks",              x: 1460, y: 430, mag: 2,
        desc: "Offizielle SDKs für TypeScript, Python, Java, Kotlin, C# kapseln Transport, JSON-RPC-Framing und Capability-Negotiation. FastMCP (Python) und der TS-SDK bieten deklarative Decorator-/Builder-APIs für Tools und Resources, reduzieren Boilerplate gegenüber der rohen Protokoll-Implementierung deutlich." },
      { id: "mcp-client-config",  label: "client config",     x: 1250, y: 170, mag: 3,
        desc: "Host-Anwendungen (Claude Desktop, IDEs) registrieren Server über eine Konfigurationsdatei mit Kommando, Argumenten und Umgebungsvariablen pro Server. Jeder konfigurierte Server läuft als eigener Prozess/eigene Verbindung, der Host aggregiert alle verfügbaren Tools über Server-Grenzen hinweg für das Modell." },
      { id: "mcp-security",       label: "sandboxing",        x: 1100, y: 170, mag: 2,
        desc: "Tool-Server laufen mit den Rechten des startenden Prozesses, es gibt keine eingebaute Sandbox im Protokoll selbst. Least-Privilege gilt für Dateisystem-Zugriff (Roots), Netzwerk-Zugriff und Secrets. Prompt-Injection über Resource-Inhalte ist ein reales Risiko: von Tools gelieferte Daten sind fremde Eingabe, kein vertrauenswürdiger Code." },
    ],
    lines: [
      ["mcp-protocol", "server-lifecycle"],
      ["mcp-protocol", "mcp-tools"],
      ["mcp-protocol", "mcp-resources"],
      ["mcp-protocol", "mcp-prompts"],
      ["server-lifecycle", "transport-stdio"],
      ["server-lifecycle", "transport-http-sse"],
      ["mcp-tools", "tool-schema"],
      ["mcp-tools", "mcp-sdk"],
      ["mcp-resources", "mcp-roots"],
      ["mcp-resources", "transport-http-sse"],
      ["transport-http-sse", "mcp-auth"],
      ["transport-stdio", "mcp-client-config"],
      ["mcp-sdk", "mcp-client-config"],
      ["mcp-sampling", "mcp-protocol"],
      ["mcp-sampling", "mcp-tools"],
      ["mcp-roots", "mcp-security"],
      ["mcp-auth", "mcp-security"],
      ["tool-schema", "mcp-sdk"],
      ["mcp-client-config", "mcp-security"],
      ["mcp-prompts", "mcp-sdk"],
    ],
  },

  //------------------------------------------------------ A2A & TASK STORAGE
  {
    id: "a2a",
    name: "A2A & TASK STORAGE",
    catalog: "C-03",
    hue: 100,
    cx: 780, cy: 780,
    stars: [
      { id: "a2a-protocol",       label: "a2a protocol",      x: 170, y: 150, mag: 1,
        desc: "Agent2Agent Protocol (A2A), ursprünglich von Google entwickelt und 2025 an die Linux Foundation übergeben, standardisiert die Kommunikation zwischen autonomen KI-Agenten unterschiedlicher Frameworks/Anbieter. JSON-RPC 2.0 über HTTP(S) als Transport-Basis. Ergänzt MCP: MCP verbindet ein Modell mit Tools/Daten, A2A verbindet Agenten untereinander auf Peer-Ebene." },
      { id: "agent-card",         label: "agent card",        x: 250, y: 260, mag: 1,
        desc: "Maschinenlesbares Capability-Manifest unter /.well-known/agent.json. Enthält Name, Beschreibung, unterstützte Skills, Endpunkt-URL, Input/Output-Modalitäten und die geforderten Security-Schemes. Ermöglicht einem Client, vor dem ersten Aufruf zu prüfen, ob ein Agent die benötigte Fähigkeit überhaupt anbietet, analog zu einer OpenAPI-Spec für Agenten." },
      { id: "task-lifecycle",     label: "task lifecycle",    x: 310, y: 390, mag: 1,
        desc: "Zentrale Zustandsmaschine jeder Interaktion: submitted → working → (input-required) → completed/failed/canceled. input-required pausiert den Task, bis der Client fehlende Angaben nachliefert, ohne dass der Kontext verloren geht. Jeder Task trägt eine eindeutige, vom Client vergebene Task-ID." },
      { id: "task-store",         label: "task store",        x: 430, y: 460, mag: 1,
        desc: "Persistenzschicht, die den aktuellen Zustand, die Nachrichtenhistorie und erzeugte Artefakte pro Task-ID vorhält. Notwendig, weil A2A-Tasks über mehrere HTTP-Requests und ggf. Stunden hinweg laufen können, nicht in einem einzigen Request/Response-Zyklus. tasks/get liest den aktuellen Stand, unabhängig davon, welche Server-Instanz den Task ursprünglich angenommen hat." },
      { id: "artifacts",          label: "artifacts",         x: 500, y: 340, mag: 2,
        desc: "Strukturierte Ergebnisobjekte eines Tasks, bestehend aus Parts (TextPart, FilePart, DataPart). Ein Task kann mehrere Artefakte über seine Laufzeit produzieren, etwa Zwischenergebnisse bei langlaufenden Analysen. Getrennt von den Status-Updates des Task-Lifecycle, um Nutzdaten von Steuerinformationen zu trennen." },
      { id: "push-notifications", label: "push notifications", x: 620, y: 240, mag: 2,
        desc: "Webhook-basierte Benachrichtigung für lange oder asynchron laufende Tasks: der Client registriert per tasks/pushNotification/set eine Callback-URL, der Server pusht Status-Änderungen statt dass der Client pollt oder eine offene Verbindung hält. Wichtig bei Agenten, die Minuten bis Stunden für eine Aufgabe benötigen." },
      { id: "streaming-sse-a2a",  label: "sse streaming",     x: 700, y: 320, mag: 2,
        desc: "tasks/sendSubscribe liefert Status- und Artefakt-Updates als Server-Sent-Event-Stream in Echtzeit, statt auf den finalen Task-Zustand zu warten. Client kann Zwischenfortschritt (working-Updates, Teil-Artefakte) direkt anzeigen. Reconnect via tasks/resubscribe setzt einen unterbrochenen Stream an der letzten bekannten Position fort." },
      { id: "multi-turn",         label: "multi-turn",        x: 780, y: 480, mag: 2,
        desc: "Über den input-required-Status kann ein Remote-Agent aktiv Rückfragen stellen, etwa fehlende Parameter oder eine Bestätigung, bevor er fortfährt. Der Task bleibt dabei geöffnet, die bisherige Historie geht nicht verloren. Unterscheidet A2A von reinen Fire-and-Forget-Aufrufen klassischer APIs." },
      { id: "agent-discovery",    label: "agent discovery",   x: 860, y: 380, mag: 3,
        desc: "Auffinden verfügbarer Agenten über bekannte Registries, Verzeichnisdienste oder direkt verlinkte Agent-Card-URLs. In geschlossenen Systemen häufig eine interne Registry mit Katalog aller erreichbaren Agenten samt Skill-Tags, um Orchestratoren die passende Agent-Auswahl pro Teilaufgabe zu ermöglichen." },
      { id: "auth-a2a",           label: "auth (a2a)",        x: 730, y: 560, mag: 2,
        desc: "Security-Schemes analog zu OpenAPI (API-Key, OAuth2 Client Credentials, OpenID Connect), deklariert direkt in der Agent Card. Der aufrufende Client wählt ein unterstütztes Schema und authentifiziert sich beim Task-Endpunkt. Getrennt von Ende-zu-Ende-Verschlüsselung, die auf Transport-Ebene (TLS) läuft." },
      { id: "idempotency",        label: "idempotency",       x: 420, y: 580, mag: 3,
        desc: "Da Task-IDs vom Client vergeben werden, wird ein erneuter Aufruf mit derselben ID als Fortsetzung desselben Tasks behandelt statt als Duplikat. Wichtig bei Netzwerk-Retries: ein Timeout auf Client-Seite darf nicht zu doppelt ausgeführten Aktionen auf Server-Seite führen." },
      { id: "state-persistence",  label: "state backend",     x: 560, y: 150, mag: 2,
        desc: "Konkretes Backend hinter dem Task Store: Redis für schnellen Zugriff auf aktive Tasks, Postgres/Objektspeicher für Langzeit-Historie und große Artefakte. Muss nebenläufige Updates verschiedener Server-Instanzen konsistent handhaben, insbesondere bei horizontal skalierten Agent-Deployments hinter einem Load Balancer." },
      { id: "orchestrator-agent", label: "orchestrator",      x: 880, y: 560, mag: 2,
        desc: "Ein übergeordneter Agent zerlegt eine komplexe Anfrage in Teilaufgaben und delegiert sie per A2A an spezialisierte Remote-Agenten, sammelt deren Artefakte ein und fügt sie zum Gesamtergebnis zusammen. Nutzt Agent Cards zur Auswahl des passenden Agenten pro Teilaufgabe." },
      { id: "context-id",         label: "context id",        x: 610, y: 640, mag: 3,
        desc: "Context-ID gruppiert mehrere zusammenhängende Tasks, etwa wenn ein Orchestrator im Rahmen einer einzigen Nutzeranfrage mehrere Sub-Tasks an verschiedene Agenten verteilt. Erlaubt, den gesamten Gesprächs-/Arbeitszusammenhang über Task-Grenzen hinweg nachzuvollziehen." },
    ],
    lines: [
      ["a2a-protocol", "agent-card"],
      ["a2a-protocol", "task-lifecycle"],
      ["a2a-protocol", "artifacts"],
      ["a2a-protocol", "auth-a2a"],
      ["agent-card", "auth-a2a"],
      ["agent-card", "agent-discovery"],
      ["task-lifecycle", "task-store"],
      ["task-lifecycle", "multi-turn"],
      ["task-lifecycle", "idempotency"],
      ["task-store", "state-persistence"],
      ["task-store", "artifacts"],
      ["artifacts", "streaming-sse-a2a"],
      ["push-notifications", "task-lifecycle"],
      ["push-notifications", "streaming-sse-a2a"],
      ["streaming-sse-a2a", "multi-turn"],
      ["multi-turn", "context-id"],
      ["agent-discovery", "orchestrator-agent"],
      ["orchestrator-agent", "context-id"],
      ["orchestrator-agent", "task-store"],
      ["idempotency", "task-store"],
      ["state-persistence", "orchestrator-agent"],
    ],
  },
];

// Cross-domain relationships, drawn as brighter labeled arcs.
window.CROSS_EDGES = [
  { from: "mcp-sampling",        to: "vllm",               label: "Sampling nutzt LLM-Inferenz-Backend" },
  { from: "mcp-tools",           to: "guided-decoding",    label: "Tool-Calls als constrained JSON-Ausgabe" },
  { from: "tool-schema",         to: "guided-decoding",    label: "JSON-Schema treibt Constrained Decoding" },
  { from: "transport-http-sse",  to: "streaming-sse",      label: "gemeinsames SSE-Streaming-Pattern" },
  { from: "mcp-protocol",        to: "load-balancing",     label: "Requests über mehrere Inferenz-Instanzen geroutet" },

  // A2A ↔ MCP / LLM Serving
  { from: "a2a-protocol",        to: "mcp-protocol",       label: "komplementär: Agent-zu-Agent vs. Agent-zu-Tool" },
  { from: "orchestrator-agent",  to: "mcp-tools",          label: "delegiert Teilaufgaben via Tool-Calls" },
  { from: "auth-a2a",            to: "mcp-auth",           label: "gleiches OAuth 2.1 Security-Pattern" },
  { from: "streaming-sse-a2a",   to: "streaming-sse",      label: "gemeinsames SSE-Streaming-Pattern" },
  { from: "push-notifications",  to: "transport-http-sse", label: "Webhook/SSE als gemeinsame Transport-Basis" },
];
