// Topic constellations — stars + intra-cluster links + cross-domain edges.
// Positions are hand-picked for the landscape (1600x1000) default view; Auto-Layout
// recalculates them from scratch based on connections.

window.CONSTELLATIONS = [
  //------------------------------------------------------------------ JVM
  {
    id: "jvm",
    name: "JVM BUILDS",
    catalog: "C-01",
    hue: 38,
    cx: 400, cy: 300,
    stars: [
      { id: "pom-xml",        label: "pom.xml",         x: 170, y: 150, mag: 2,
        desc: "Zentrale Maven-Konfig. java.version=25, start-class (Voraussetzung für AOT), spring-boot-maven-plugin mit <layers> + process-aot + repackage. Observability-Dependencies als eigene Gruppe — korrespondiert mit der observability-dependencies-Schicht in layers.xml." },
      { id: "maven-cache",    label: "maven cache",     x: 250, y: 260, mag: 3,
        desc: "BuildKit Mount-Cache (--mount=type=cache,target=/root/.m2) persistiert das lokale Maven-Repository zwischen Docker-Builds. dependency:go-offline lädt alle Abhängigkeiten vorab — Folge-Builds brauchen keine Netzwerkzugriffe für bekannte Artefakte." },
      { id: "jdeps",          label: "jdeps",           x: 310, y: 390, mag: 2,
        desc: "Analysiert Java-Modulabhängigkeiten der extrahierten JAR-Layer. --print-module-deps + --multi-release 25 erzeugen eine präzise Liste aller benötigten JDK-Module. Output (modules.txt) fließt direkt in jlink." },
      { id: "java-modules",   label: "java modules",    x: 430, y: 460, mag: 1,
        desc: "Explizite Modulliste für jlink — nur diese Module landen im Custom-JRE, alles andere fällt weg. java.base, jdk.crypto.ec, jdk.charsets. java.desktop (Spring PropertyEditor), java.management + jdk.management (JMX, Metriken, GC), jdk.zipfs (JAR-Zugriff), java.sql (JPA), java.naming (Jetty JNDI), jdk.unsupported (Objenesis/CGLIB), java.security.jgss/sasl (Kerberos). Ein vollständiges JDK wäre 300+ MB — das Custom-JRE kommt auf ~60 MB." },
      { id: "jlink",          label: "jlink",           x: 500, y: 340, mag: 1,
        desc: "Erzeugt aus der jdeps-Modulliste ein maßgeschneidertes minimales JRE. --strip-debug, --compress zip-9, --no-man-pages. Laufzeit-Optionen wie ZGC und ExitOnOutOfMemoryError werden via --add-options direkt ins JRE gebacken." },
      { id: "cds-base",       label: "cds base",        x: 620, y: 240, mag: 2,
        desc: "Class Data Sharing Basis-Archiv. java -Xshare:dump erzeugt ein Shared Archive des Custom JRE. Beim App-Start direkt in den Speicher gemappt — Klassen-Metadaten müssen nicht neu gelesen werden." },
      { id: "appcds",         label: "appcds",          x: 700, y: 320, mag: 1,
        desc: "Application Class Data Sharing erweitert CDS auf Anwendungsklassen. -XX:ArchiveClassesAtExit=app.jsa mit spring.context.exit=onRefresh trainiert beim Build alle beim Spring-Start geladenen Klassen. Aktiviert via -XX:SharedArchiveFile." },
      { id: "spring-aot",     label: "spring aot",      x: 590, y: 430, mag: 1,
        desc: "Spring Boot AOT-Compilation generiert beim Build statische Proxy-Klassen und Bean-Definitionen via spring-boot:process-aot. Reduziert Reflection zur Laufzeit. -Dspring.aot.enabled=true aktiviert den AOT-Pfad. Voraussetzung für effizientes AppCDS-Training." },
      { id: "zgc",            label: "zgc",             x: 360, y: 200, mag: 2,
        desc: "Z Garbage Collector für niedrige Pausen unabhängig von Heap-Größe. Via --add-options in jlink ins JRE eingebettet, -XX:+UseZGC beim Start aktiviert. ExitOnOutOfMemoryError + MaxRAMPercentage=80." },
      { id: "layered-jar",    label: "layered jar",     x: 780, y: 480, mag: 2,
        desc: "Spring Boot JAR Layering extrahiert das Fat-JAR in Schichten: dependencies, observability-dependencies, spring-boot-loader, snapshot-dependencies, application-resources, application. Stabile Schichten in frühe Docker-Layers — nur application invalidiert den Cache." },
      { id: "layers-xml",     label: "layers.xml",      x: 860, y: 380, mag: 3,
        desc: "Konfiguriert Schichten-Reihenfolge nach Änderungshäufigkeit: dependencies → observability-dependencies → spring-boot-loader → snapshot-dependencies → application-resources → application. Stabilste zuerst für optimales Docker-Cache-Verhalten." },
      { id: "multi-stage",    label: "multi-stage",     x: 730, y: 560, mag: 1,
        desc: "Dreistufiger Docker-Build. Stage 1: Spring AOT. Stage 2: jdeps → jlink → CDS + AppCDS. Stage 3: distroless/cc, kopiert nur Custom-JRE + Layer-Verzeichnisse. Keine Build-Tools im finalen Image." },
      { id: "distroless",     label: "distroless/cc",   x: 880, y: 560, mag: 2,
        desc: "gcr.io/distroless/cc als Runtime-Base. Keine Shell, kein Paketmanager. Enthält nur libc — die JVM benötigt glibc/libstdc++ als Fundament. Läuft als nonroot (65532)." },
      { id: "entrypoint-sh",  label: "entrypoint.sh",   x: 560, y: 620, mag: 3,
        desc: "Orchestriert JVM-Start. -Dspring.aot.enabled=true, -XX:SharedArchiveFile=app.jsa, -XX:+UseZGC, -XX:MaxRAMPercentage=80, -XX:+ExitOnOutOfMemoryError. JarLauncher startet aus extrahierten Layered-JAR-Verzeichnissen." },
      { id: "buildkit",       label: "buildkit",        x: 420, y: 580, mag: 2,
        desc: "Docker Build-Engine, seit Docker 23.0 Standard (DOCKER_BUILDKIT=1 nicht mehr nötig). --mount=type=cache persistiert Maven-Repository und Layer-Cache zwischen Builds ohne COPY-Overhead. --mount=type=bind für schreibgeschützte Source-Mounts. Parallele Stage-Ausführung bei unabhängigen Stages. buildx für Multi-Arch-Images (linux/amd64 + linux/arm64)." },
      { id: "builder-base",   label: "builder base",    x: 560, y: 150, mag: 2,
        desc: "JDK-Builder-Image für Stage 1 (AOT) und Stage 2 (jlink/CDS/AppCDS). eclipse-temurin:25-jdk (Adoptium — TCK-zertifiziert, meistgenutztes Community-JDK). amazoncorretto:25-al2023 (Amazon, Graviton-optimiert, LTS). OpenShift/Red Hat: registry.access.redhat.com/ubi9/openjdk-21 — Red Hat Build of OpenJDK auf UBI9, RHEL-kompatibel, für OpenShift zertifiziert und empfohlen; ubi9-minimal als kompaktere Builder-Variante." },
    ],
    lines: [
      ["pom-xml", "maven-cache"],
      ["pom-xml", "spring-aot"],
      ["pom-xml", "layered-jar"],
      ["pom-xml", "layers-xml"],
      ["maven-cache", "multi-stage"],
      ["jdeps", "jlink"],
      ["jdeps", "java-modules"],
      ["jdeps", "layered-jar"],
      ["jlink", "java-modules"],
      ["jlink", "cds-base"],
      ["jlink", "distroless"],
      ["jlink", "zgc"],
      ["cds-base", "appcds"],
      ["appcds", "spring-aot"],
      ["spring-aot", "layered-jar"],
      ["spring-aot", "multi-stage"],
      ["layered-jar", "layers-xml"],
      ["layered-jar", "multi-stage"],
      ["multi-stage", "distroless"],
      ["multi-stage", "entrypoint-sh"],
      ["entrypoint-sh", "appcds"],
      ["entrypoint-sh", "zgc"],
      ["entrypoint-sh", "spring-aot"],
      ["zgc", "java-modules"],
      ["maven-cache", "buildkit"],
      ["buildkit", "multi-stage"],
      ["builder-base", "multi-stage"],
      ["builder-base", "jlink"],
      ["builder-base", "spring-aot"],
      ["distroless", "entrypoint-sh"],
      ["cds-base", "entrypoint-sh"],
      ["layers-xml", "entrypoint-sh"],
    ],
  },

  //-------------------------------------------------------------- GITOPS
  {
    id: "gitops",
    name: "GITOPS",
    catalog: "C-02",
    hue: 195,
    cx: 1180, cy: 280,
    stars: [
      { id: "kaniko",           label: "kaniko",          x: 1110, y: 340, mag: 1,
        desc: "Baut Container-Images im Cluster ohne Docker-Daemon. Kontext per git://-URL, --destination pusht parallel auf Docker Hub und :latest. Docker-Creds via regcred-Secret in /kaniko/.docker. Kein privilegierter Container." },
      { id: "kaniko-layer-cache", label: "layer cache",   x: 1240, y: 400, mag: 2,
        desc: "Kaniko Layer-Cache in der Cluster-Registry. --cache=true + --cache-repo. Unveränderte Basis-Layer (distroless, Custom-JRE) werden aus dem Cache gelesen. Harmoniert mit Layered-JAR — nur application-Layer wird neu gebaut." },
      { id: "cluster-registry", label: "cluster registry", x: 1380, y: 340, mag: 2,
        desc: "In-Cluster registry:2 als containerd-Mirror. Löst Image Rate Limits: containerd-Mirror-Config leitet alle Pulls über die lokale Registry. regcred bleibt für den Push bestehen, Registry übernimmt nur den Pull-Pfad." },
      { id: "git-update",       label: "git update",      x: 980,  y: 420, mag: 2,
        desc: "Alpine-Git-Container committed nach jedem Build den neuen image.tag in values.yaml. GitHub-Token aus Secret → clone → sed → diff → commit → push. Idempotent via git diff --cached --quiet." },
      { id: "argo-apps",        label: "argocd",          x: 1120, y: 490, mag: 1,
        desc: "ArgoCD Application-Ressource als zentrales GitOps-Objekt: repoURL (Helm-Chart-Repo), targetRevision (Branch/Tag), path (Chart-Verzeichnis), destination (Cluster + Namespace). Sync-Policy mit automated.prune (verwaiste Ressourcen werden gelöscht) und selfHeal (Cluster-Abweichungen werden sofort zurückgesetzt). Health-Status aggregiert Deployment, Service, Route. git-update triggert indirekt: der values.yaml-Commit löst automatischen Sync aus. App-of-Apps-Pattern verwaltet viele Applications als eine." },
      { id: "argo-projects",    label: "projects",        x: 1270, y: 540, mag: 3,
        desc: "ArgoCD Projects scopen Application-Gruppen: erlaubte Source-Repos, Destination-Cluster, Namespaces. Verhindert, dass eine Application beliebige Cluster oder Namespaces als Sync-Ziel verwenden kann. selector.py ist ein internes Hilfsskript, das Applications anhand ihrer Labels (z. B. team=backend, env=prod) automatisch dem passenden Project zuweist — vermeidet manuelle AppProject-Pflege bei vielen Applications." },
      { id: "helm",             label: "helm",            x: 980,  y: 560, mag: 1,
        desc: "Paketmanager. Chart.yaml + values.yaml + templates/. git-update schreibt direkt in values.yaml — ArgoCD synct. Seit Helm 3.8 OCI-Registry: Charts als OCI-Artefakte neben Images, ArgoCD unterstützt type: oci direkt. Hooks (pre-install, post-upgrade) für Migrationen/Smoke-Tests." },
      { id: "bitbucket-webhook",  label: "bitbucket",       x: 850,  y: 200, mag: 2,
        desc: "Bitbucket Server triggert CI via HTTP-Webhook bei Push-Events. Repository-Webhook konfiguriert EventListener-URL. Payload enthält Branch, Commit-SHA, geänderte Dateien. Personal Access Token oder HTTP-Access-Token für git-clone im Tekton-Step. Branch-Filter im CEL-Interceptor — nur main/release-Branches triggern den Build." },
      { id: "tekton-triggers",    label: "tekton triggers", x: 940,  y: 310, mag: 2,
        desc: "Verbindet Bitbucket-Webhooks mit Tekton-Pipelines. EventListener empfängt HTTP-POST von Bitbucket als Service im Cluster. TriggerBinding extrahiert Felder (branch, commit SHA, repo URL) aus dem Webhook-Payload. TriggerTemplate erstellt PipelineRun-Objekt mit extrahierten Werten als Params. CEL-Interceptor filtert Events: nur Push auf konfigurierten Branches." },
      { id: "tekton-pipeline",    label: "tekton pipeline", x: 1020, y: 200, mag: 1,
        desc: "Kubernetes-native CI-Pipeline. Pipeline-Ressource definiert Tasks als DAG. Tasks: git-clone (Bitbucket via SSH-Key), maven-build (mit Cache-PVC für .m2), kaniko-build, image-push in private Registry, git-update für values.yaml. PipelineRun instanziiert eine konkrete Ausführung — Params (IMAGE_TAG, GIT_REVISION) kommen aus TriggerBinding. PVC als Workspace für Source-Sharing zwischen Tasks." },
      { id: "private-registry",   label: "private registry", x: 1440, y: 230, mag: 2,
        desc: "Private Container-Registry für finale Images — getrennt von der In-Cluster-Cache-Registry. Quay (Red Hat, RBAC per Repository, Security Scanning) oder Harbor (Open Source, Trivy-Integration, Replikation zwischen Sites). Kaniko pushed via --destination. ImagePullSecret im Deployment-Namespace. Pull erfolgt beim Cluster direkt aus der privaten Registry, nicht über die Cache-Registry." },
      { id: "k8s-workload",       label: "k8s workload",    x: 1460, y: 430, mag: 2,
        desc: "Kubernetes Deployment + Service als ArgoCD-Sync-Ziel. Deployment: replicas, image-Tag aus values.yaml, resources (requests/limits), livenessProbe /actuator/health, readinessProbe /actuator/health/readiness. Service: ClusterIP auf Container-Port. OpenShift Route für externen TLS-Zugriff (Edge-Termination). HPA skaliert nach CPU oder Custom-Metriken (via KEDA)." },
      { id: "serviceaccount-rbac", label: "rbac",           x: 1250, y: 170, mag: 3,
        desc: "ServiceAccounts + Roles/RoleBindings für alle GitOps-Komponenten nach Least-Privilege. Tekton-SA: pull aus Cluster-Registry, push in private Registry (imagePullSecret + push-Secret). Kaniko-SA: OpenShift SCC anyuid oder dedizierte SCC (kein privilegierter Container). ArgoCD-SA: get/list/watch/patch für Deployment/Service/Route/ConfigMap. Kein Wildcard-Verb (*) in produktiven Roles." },
      { id: "secret-management",  label: "secrets",         x: 1100, y: 170, mag: 2,
        desc: "Secrets für Registry-Credentials, Bitbucket-Token, TLS-Zertifikate. Sealed Secrets: asymmetrisch verschlüsselt mit Cluster-Public-Key — SealedSecret im Bitbucket-Repo versionierbar, nur der Cluster entschlüsselt. External Secrets Operator: synchronisiert aus HashiCorp Vault oder OpenShift Secrets Store — Single Source of Truth außerhalb des Clusters, automatische Rotation. Tekton: Secret als Workspace-Binding oder EnvFrom im TaskSpec." },
    ],
    lines: [
      ["kaniko", "kaniko-layer-cache"],
      ["kaniko", "cluster-registry"],
      ["kaniko-layer-cache", "cluster-registry"],
      ["git-update", "argo-apps"],
      ["argo-apps", "argo-projects"],
      ["argo-apps", "helm"],
      ["helm", "git-update"],
      ["helm", "cluster-registry"],
      ["bitbucket-webhook", "tekton-triggers"],
      ["tekton-triggers", "tekton-pipeline"],
      ["tekton-pipeline", "kaniko"],
      ["tekton-pipeline", "git-update"],
      ["kaniko", "private-registry"],
      ["argo-apps", "k8s-workload"],
      ["helm", "k8s-workload"],
      ["k8s-workload", "private-registry"],
      ["serviceaccount-rbac", "tekton-pipeline"],
      ["serviceaccount-rbac", "kaniko"],
      ["serviceaccount-rbac", "argo-apps"],
      ["secret-management", "kaniko"],
      ["secret-management", "git-update"],
      ["secret-management", "tekton-pipeline"],
      ["secret-management", "serviceaccount-rbac"],
      ["secret-management", "argo-apps"],
      ["serviceaccount-rbac", "git-update"],
      ["cluster-registry", "k8s-workload"],
    ],
  },

  //------------------------------------------------------------- OBSERVABILITY
  {
    id: "obs",
    name: "OBSERVABILITY",
    catalog: "C-03",
    hue: 155,
    cx: 1180, cy: 760,
    stars: [
      { id: "actuator",           label: "actuator",           x: 1000, y: 640, mag: 1,
        desc: "Spring Boot Actuator exponiert /actuator/health, /actuator/prometheus (primärer Scrape-Endpunkt), /actuator/info (Git-Commit, Build-Version). management.endpoints.web.exposure.include steuert Sichtbarkeit. Typisch auf Management-Port 8081 im distroless-Container." },
      { id: "micrometer",         label: "micrometer",         x: 1120, y: 720, mag: 1,
        desc: "Metriken-Fassade für JVM — SLF4J für Metriken. Counter, Gauge, Timer, DistributionSummary mit Tags für mehrdimensionale Filterung. PrometheusMeterRegistry serialisiert. Automatische JVM-Metriken (ZGC: zgc.*, pause.*), Heap, Threads. HTTP-Server-Metriken (http.server.requests) mit Methode/URI/Status-Tags." },
      { id: "prometheus-scrape",  label: "prometheus",         x: 1260, y: 680, mag: 1,
        desc: "Pull-basiertes Scraping. ServiceMonitor (Operator) definiert Scrape-Targets: matchLabels, endpoints.path=/actuator/prometheus, interval=15s. TSDB speichert Zeitreihen, PromQL aggregiert (rate, histogram_quantile). Recording Rules materialisieren häufige Queries." },
      { id: "alertmanager",       label: "alertmanager",       x: 1410, y: 660, mag: 2,
        desc: "Empfängt Firing-Alerts und übernimmt Routing, Grouping, Inhibition, Silencing. Receiver (Slack/PagerDuty/E-Mail). Grouping verhindert Alert-Flooding, Inhibition unterdrückt nachgelagerte Alerts, Silencing für Wartungsfenster. AlertmanagerConfig-CRD für namespace-scoped Routing." },
      { id: "grafana",            label: "grafana",            x: 1300, y: 820, mag: 1,
        desc: "Visualisiert Metriken (Prometheus), Traces (Tempo) und Logs (Loki/OpenSearch) im einheitlichen UI. Dashboard-as-Code (JSON) via Git + Grafana Operator. Exemplars verbinden Metrik-Datenpunkte direkt mit Trace-IDs — ein Klick springt zum Request-Trace. Unified Alerting: Alertmanager ist direkt integriert." },
      { id: "opentelemetry",      label: "opentelemetry",      x: 960,  y: 800, mag: 1,
        desc: "Vendor-neutraler Standard für Observability-Daten. Definiert drei Signal-Typen: Traces (Spans mit TraceID/ParentSpanID), Metrics (Gauge, Counter, Histogram) und Logs (LogRecord mit Trace-Kontext). Semantic Conventions legen einheitliche Attributnamen fest (http.request.method, db.system, messaging.destination.name). OTLP als einheitliches Wire-Protokoll — ein Exporter für alle Backends." },
      { id: "otel-collector",     label: "otel collector",     x: 1080, y: 880, mag: 2,
        desc: "Zentraler Telemetrie-Hub. Pipeline: Receivers (OTLP, Jaeger, Zipkin) → Processors (Batch, MemoryLimiter, Tail-Based Sampling) → Exporters (Tempo, OpenSearch, Prometheus). Tail-Based Sampling: 100 % Retention bei Fehlern, Sampling bei erfolgreichen langsamen Requests. DaemonSet (Agent) oder Deployment (Gateway). Ersetzt Logstash im OLK-Stack." },
      { id: "tempo",              label: "tempo",              x: 1200, y: 950, mag: 2,
        desc: "Distributed-Trace-Backend im OTLP-Format, skalierbar auf Objektspeicher (S3/GCS/MinIO). Spans mit TraceID, ParentSpanID, Attributes. TraceQL: {.http.status_code=500 && duration > 1s}. Exemplars in Grafana-Panels linken direkt zum Trace." },
      { id: "olk-stack",          label: "olk stack",          x: 850,  y: 920, mag: 2,
        desc: "OpenSearch + Logstash + Kibana — OpenSearch-Fork-Alternative zu ELK. Vollständig indizierter JSON-Store, Volltextsuche über alle Felder. OTel-Collector kann Logstash ersetzen (OTLP-Receiver → opensearch-Exporter). ILM rotiert Indices automatisch. Höherer Speicherbedarf als Loki, aber schnellere Ad-hoc-Queries." },
      { id: "opensearch-trace",   label: "opensearch trace",   x: 780,  y: 820, mag: 3,
        desc: "OpenSearch Trace Analytics als Tempo-Alternative. Data Prepper empfängt Spans via OTLP und schreibt in ss4o-Indices. Traces und Logs im selben Backend — keine separate Tempo-Instanz. Service Map + Waterfall-View via OpenSearch Dashboards Trace Analytics Plugin." },
      { id: "servicemonitor",      label: "servicemonitor",     x: 1130, y: 615, mag: 3,
        desc: "Prometheus Operator CRD für deklarative Scrape-Konfiguration. ServiceMonitor wählt Services via labelSelector und definiert endpoints.path, port, interval, scheme. PodMonitor scrapt Pods direkt ohne Service. Operator reconciliert CRDs in Prometheus-Scrape-Config — keine manuelle prometheus.yml-Pflege. Namespace-Scoping über namespaceSelector." },
      { id: "prometheusrule",      label: "prometheus rule",    x: 1390, y: 750, mag: 3,
        desc: "Prometheus Operator CRD für Alert- und Recording-Rules. PrometheusRule gruppiert rules: AlertingRules (expr, for, labels, annotations) und RecordingRules (materialisierte PromQL-Queries). Operator lädt Rules in Prometheus hot — kein Restart. Severity-Labels (critical/warning) steuern Alertmanager-Routing." },
      { id: "node-exporter",      label: "node exporter",      x: 1450, y: 820, mag: 3,
        desc: "Host-Metriken als DaemonSet auf Port 9100. CPU (node_cpu_seconds_total), Memory (node_memory_MemAvailable_bytes), Disk (node_disk_read_bytes_total), Netzwerk, Filesystem-Nutzung. Ergänzt die App-Perspektive (Micrometer) um die Host-Perspektive." },
      { id: "kube-state-metrics", label: "kube-state-metrics", x: 1500, y: 920, mag: 3,
        desc: "Prometheus-Exporter für Kubernetes-Objekt-Zustand. Deployments (Soll/Ist-Replicas), Pods (Restarts für CrashLoopBackOff), HPA, PVC, Jobs. Zusammen mit Node Exporter: Objekt-Zustand + Hardware-Zustand = vollständiges Cluster-Monitoring." },
    ],
    lines: [
      ["actuator", "micrometer"],
      ["actuator", "servicemonitor"],
      ["actuator", "prometheus-scrape"],
      ["servicemonitor", "prometheus-scrape"],
      ["micrometer", "prometheus-scrape"],
      ["micrometer", "opentelemetry"],
      ["prometheus-scrape", "prometheusrule"],
      ["prometheus-scrape", "alertmanager"],
      ["prometheusrule", "alertmanager"],
      ["prometheus-scrape", "grafana"],
      ["alertmanager", "grafana"],
      ["opentelemetry", "otel-collector"],
      ["opentelemetry", "tempo"],
      ["otel-collector", "tempo"],
      ["otel-collector", "olk-stack"],
      ["otel-collector", "opensearch-trace"],
      ["tempo", "grafana"],
      ["olk-stack", "grafana"],
      ["opensearch-trace", "olk-stack"],
      ["opensearch-trace", "grafana"],
      ["node-exporter", "prometheus-scrape"],
      ["node-exporter", "grafana"],
      ["kube-state-metrics", "prometheus-scrape"],
      ["kube-state-metrics", "node-exporter"],
      ["kube-state-metrics", "grafana"],
      ["actuator", "otel-collector"],
    ],
  },

  //--------------------------------------------------------------- OTEL JAVA AGENT
  {
    id: "agent",
    name: "OTEL JAVA AGENT",
    catalog: "C-04",
    hue: 320,
    cx: 400, cy: 780,
    stars: [
      { id: "javaagent",         label: "java agent",          x: 400, y: 780, mag: 1,
        desc: "opentelemetry-javaagent.jar via -javaagent Flag. Instrumentiert die JVM beim Start via ByteBuddy — kein Quellcode-Eingriff nötig. Konfiguration komplett über Umgebungsvariablen (OTEL_*) oder System Properties. Unterstützt 100+ Bibliotheken out-of-the-box." },
      { id: "bytecode-instr",    label: "bytecode instr.",     x: 230, y: 710, mag: 2,
        desc: "ByteBuddy transformiert Klassen beim Laden via Java Instrumentation API. ElementMatcher greift auf Methoden-Signaturen — Advice-Klassen injizieren Span-Start/Stop. Kein Proxy, kein Weaving zur Compile-Zeit. AgentBuilder registriert alle Instrumentierungen beim JVM-Start." },
      { id: "http-server-instr", label: "http server",         x: 200, y: 620, mag: 2,
        desc: "Spring MVC, Spring WebFlux, JAX-RS, Servlet — jeder eingehende Request erzeugt einen SERVER-Span. traceparent/tracestate aus dem Header extrahiert (W3C Trace Context). Attribute nach Semantic Conventions: http.request.method, url.path, http.response.status_code, server.address." },
      { id: "http-client-instr", label: "http client",         x: 360, y: 630, mag: 3,
        desc: "Apache HttpClient 4/5, OkHttp, HttpURLConnection, Spring WebClient, Feign. Ausgehende Calls als CLIENT-Span. traceparent wird automatisch injiziert — lückenlose Propagation ohne Code. http.request.method, server.address, url.full als Attributes." },
      { id: "jdbc-instr",        label: "jdbc",                x: 540, y: 650, mag: 2,
        desc: "Alle JDBC-Treiber: PostgreSQL, MySQL, H2, Oracle. db.system, db.name, db.operation, db.query.text (sanitized, ohne Werte) als Span-Attributes. Slow-Query-Erkennung via Span-Duration. Connection-Pool-Metriken (HikariCP) automatisch erfasst." },
      { id: "messaging-instr",   label: "messaging",           x: 580, y: 760, mag: 3,
        desc: "Kafka Producer/Consumer, RabbitMQ, JMS: PRODUCER/CONSUMER-Span-Kind. messaging.system, messaging.destination.name, messaging.operation als Attributes. traceparent in Message-Header propagiert Kontext über Queue-Grenzen — End-to-End-Trace über asynchrone Grenzen." },
      { id: "jvm-telemetry",     label: "jvm telemetry",       x: 550, y: 870, mag: 1,
        desc: "Automatische JVM-Metriken: jvm.memory.used/committed (Heap + NonHeap-Pools), jvm.gc.duration (ZGC: zgc.cycle.*, zgc.pause.*), jvm.thread.count, jvm.class.count, process.cpu.time. Kein Micrometer erforderlich — alle Metriken über OTLP exportiert." },
      { id: "log-correlation",   label: "log correlation",     x: 400, y: 940, mag: 2,
        desc: "Injiziert trace_id, span_id, trace_flags automatisch in den MDC (Logback, Log4j2). Logs tragen die aktuelle Trace-ID ohne Code-Änderungen. Grafana und OpenSearch können Logs direkt mit Traces korrelieren — ein Klick vom Log-Eintrag zum vollständigen Trace." },
      { id: "otlp-export",       label: "otlp export",         x: 230, y: 870, mag: 2,
        desc: "Exportiert Traces, Metrics und Logs parallel via OTLP/gRPC oder OTLP/HTTP. OTEL_EXPORTER_OTLP_ENDPOINT konfiguriert den Collector-Endpunkt. BatchSpanProcessor puffert Spans, periodic MetricReader sammelt Metriken im konfigurierbaren Intervall. Unterstützt auch Jaeger/Zipkin-Exporter." },
      { id: "resource-attrs",    label: "resource detection",  x: 320, y: 860, mag: 3,
        desc: "Erkennt Ressource-Attribute automatisch: service.name (OTEL_SERVICE_NAME), k8s.pod.name, k8s.namespace.name, k8s.node.name, container.id aus /proc/self/cgroup, host.name. Alle Spans tragen diese Attribute — Filterung nach Pod/Namespace in Grafana ohne zusätzliche Labels." },
    ],
    lines: [
      ["javaagent", "bytecode-instr"],
      ["javaagent", "otlp-export"],
      ["javaagent", "resource-attrs"],
      ["bytecode-instr", "http-server-instr"],
      ["bytecode-instr", "http-client-instr"],
      ["bytecode-instr", "jdbc-instr"],
      ["bytecode-instr", "messaging-instr"],
      ["bytecode-instr", "jvm-telemetry"],
      ["bytecode-instr", "log-correlation"],
      ["http-server-instr", "http-client-instr"],
      ["http-server-instr", "otlp-export"],
      ["http-client-instr", "otlp-export"],
      ["jdbc-instr", "otlp-export"],
      ["messaging-instr", "otlp-export"],
      ["otlp-export", "resource-attrs"],
      ["log-correlation", "otlp-export"],
      ["jvm-telemetry", "otlp-export"],
      ["resource-attrs", "log-correlation"],
    ],
  },
];

// Cross-domain relationships — drawn as brighter labeled arcs.
window.CROSS_EDGES = [
  // JVM ↔ GitOps
  { from: "kaniko",              to: "multi-stage",        label: "baut Dockerfile" },
  { from: "kaniko-layer-cache",  to: "multi-stage",        label: "beschleunigt Layer-Builds" },
  { from: "kaniko-layer-cache",  to: "layered-jar",        label: "cached stabile Layer" },
  { from: "helm",                to: "entrypoint-sh",      label: "deployt Runtime-Config" },
  { from: "tekton-pipeline",     to: "multi-stage",        label: "führt Docker-Build aus" },
  { from: "k8s-workload",        to: "entrypoint-sh",      label: "startet JVM-Prozess" },

  // JVM ↔ Observability
  { from: "java-modules",        to: "prometheus-scrape",  label: "java.management für Metriken" },
  { from: "actuator",            to: "java-modules",       label: "benötigt JMX/Management" },
  { from: "micrometer",          to: "java-modules",       label: "java.management für GC" },
  { from: "layered-jar",         to: "micrometer",         label: "observability-dep Layer" },
  { from: "zgc",                 to: "micrometer",         label: "ZGC-Metriken (pause.*, zgc.*)" },

  // GitOps ↔ Observability
  { from: "kube-state-metrics",  to: "argo-apps",          label: "beobachtet Sync-Status" },

  // OTel Java Agent ↔ anywhere
  { from: "javaagent",           to: "otel-collector",     label: "OTLP Traces/Metrics/Logs" },
  { from: "javaagent",           to: "entrypoint-sh",      label: "-javaagent Flag" },
  { from: "javaagent",           to: "multi-stage",        label: "JAR im Docker-Build hinzugefügt" },
  { from: "javaagent",           to: "k8s-workload",       label: "JAVA_TOOL_OPTIONS im Deployment" },
  { from: "jvm-telemetry",       to: "micrometer",         label: "ergänzt JVM-Metriken" },
  { from: "log-correlation",     to: "olk-stack",          label: "trace_id in Log-Feldern" },
  { from: "log-correlation",     to: "grafana",            label: "Log-zu-Trace-Korrelation" },
  { from: "http-server-instr",   to: "actuator",           label: "parallele Instrumentierung" },
];
